### ISSUE TITLE
Incorrect syntax near the keyword 'INTO'

### ISSUE THREAD

**Issue by MarkLTX** [KostovMartin/Dapper.Bulk#29]
Using Dapper.Bulk 1.5.0, getting this exception:

Exception type: System.Data.SqlClient.SqlException
Exception message: Incorrect syntax near the keyword 'INTO'.

My C# code looks like this:

        public static void PopulateCalcRefs(List<tbl_calc_refs> calcRefs)
        {
            string connStr = "XXXX";

            using (SqlConnection sqlConn = new SqlConnection(connStr))
            {
                sqlConn.Open();
                int rows = sqlConn.Execute("truncate table tbl_calc_refs");
                sqlConn.BulkInsert(calcRefs);
            }
        }

Note that the "truncate" command works, but the BulkInsert fails with the exception described above.  

The table tbl_calc_refs is defined like this.

CREATE TABLE [dbo].[tbl_calc_refs](
	[CalcTag] [VARCHAR](30) NOT NULL,
	[ReferencedTag] [VARCHAR](30) NOT NULL
) ON [PRIMARY]

The class tbl_calc_refs is declared like this.

    internal class tbl_calc_refs
    {
        public string CalcTag;
        public string ReferencedTag;
    }

According to the SQL Server Profiler, this is the command causing the exception.  Note the extra 's' in the table name.

SELECT TOP 0  INTO #TempInsert_tbl_calc_refss FROM [tbl_calc_refss] target WITH(NOLOCK);

I tried changing the class tbl_calc_refs to this.

    public class tbl_calc_refs
    {
        public string CalcTag { get; set; }
        public string ReferencedTag { get; set; }
    }

And that resulted in the following error.

Invalid object name 'tbl_calc_refss'.

**Comment by CesarD** [comment]
It happens the same to me but with read-only properties that are initialized through a constructor.

Why the need to have writable properties if the expected behavior is to just read the information from an object?

If I have some all read-only properties, the library will not read any of them and the SQL query generated will not contain any field to copy from the temp table, causing the same message on the title of this issue.
